import 'package:hive_flutter/hive_flutter.dart';
import 'logger_service.dart';
import '../mvvm/model/hike.dart';
import '../mvvm/model/track_point.dart';

/// Service for local data storage using Hive
///
/// Manages offline storage of hikes with type-safe access
class StorageService {
  StorageService._();
  static final StorageService instance = StorageService._();

  /// Box name for storing hikes
  static const String _hikesBoxName = 'hikes';

  bool _initialized = false;

  /// Initialize Hive and register adapters
  /// Must be called before using any storage operations
  Future<void> init() async {
    if (_initialized) return;

    LoggerService.i('StorageService.init: initializing Hive storage');
    // Initialize Hive
    await Hive.initFlutter();

    // Register type adapters (generated by build_runner)
    if (!Hive.isAdapterRegistered(0)) {
      LoggerService.i('StorageService.init: registering TrackPointAdapter');
      Hive.registerAdapter(TrackPointAdapter());
    }
    if (!Hive.isAdapterRegistered(1)) {
      LoggerService.i('StorageService.init: registering HikeAdapter');
      Hive.registerAdapter(HikeAdapter());
    }

    // Open boxes
    LoggerService.i('StorageService.init: opening box "$_hikesBoxName"');
    await Hive.openBox<Hike>(_hikesBoxName);

    _initialized = true;
    LoggerService.i('StorageService.init: storage initialization complete');
  }

  /// Get hikes box
  Box<Hike> get _hikesBox => Hive.box<Hike>(_hikesBoxName);

  /// Save a hike to local storage
  Future<void> saveHike(Hike hike) async {
    LoggerService.i(
      'StorageService.saveHike: saving hike ${hike.id} - ${hike.name}',
    );
    await _hikesBox.put(hike.id, hike);
  }

  /// Get all saved hikes
  /// Returns list sorted by start time (newest first)
  Future<List<Hike>> getAllHikes() async {
    LoggerService.i('StorageService.getAllHikes: retrieving all hikes');
    final hikes = _hikesBox.values.toList();
    hikes.sort((a, b) => b.startTime.compareTo(a.startTime));
    LoggerService.i('StorageService.getAllHikes: found ${hikes.length} hikes');
    return hikes;
  }

  /// Get a specific hike by ID
  Future<Hike?> getHike(String id) async {
    return _hikesBox.get(id);
  }

  /// Delete a hike by ID
  Future<void> deleteHike(String id) async {
    LoggerService.i('StorageService.deleteHike: deleting hike $id');
    await _hikesBox.delete(id);
  }

  /// Delete all hikes (for testing/cleanup)
  Future<void> deleteAllHikes() async {
    await _hikesBox.clear();
  }

  /// Get total number of saved hikes
  int getHikeCount() {
    return _hikesBox.length;
  }

  /// Check if storage is initialized
  bool get isInitialized => _initialized;
}
